### ISSUE TITLE
TAXII Service - PCAPs File: 'File' object has no attribute 'description'

### ISSUE THREAD

**Issue by packet-rat** [DSIE/crits#1]
From: https://github.com/crits/crits/pull/427

brlogan added a note 6 hours ago
I was seeing a File: Incorrect padding failure message, but only when receiving certain Samples via TAXII Agent. I eventually realized that even the Samples that were making it through without an error had bad data. After some work, I managed to trace this problem to the above line. I didn't dig very deep into the python-stix code, but it appears that STIXPackage.from_xml() does the work of base64 decoding the Sample data. So, when the above line executes, it is trying to decode already decoded data, which causes the error.
Changing data = base64.b64decode(obj.properties.data) to data = obj.properties.data seems to solve the problem.

mgoffin added a note an hour ago
I wonder if it does the same things for PCAP, RawData, and Certificate binary data...

@mgoffin:  I wonder if it does the same things for PCAP: Yes

![voila_capture 2015-03-26_09-31-54_am](https://cloud.githubusercontent.com/assets/3220193/6847216/2a9137e4-d39b-11e4-8a3d-f014ba5054eb.jpg)

[20150326-134035: Update - It turns out the PCAP at the Source CRITs didn't have a "Description".  However, entering a description and resending resulted in the same error.
![voila_capture 2015-03-26_09-42-29_am](https://cloud.githubusercontent.com/assets/3220193/6847370/8602248e-d39c-11e4-9a1f-864d5b15f895.jpg)

**Comment by mgoffin** [comment]
Already fixed in the parser_use_handlers branch...

**Comment by brlogan** [comment]
This issue was fixed in crits/crits#427, which has been replicated as 0bcc983c546ef86e1abf1c7cfa813bb0c5a8435a.
